# Generated by Django 4.2.27 on 2025-12-11 18:05

from django.db import migrations, models
import farmclassifieds.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmclassifieds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimage',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to=farmclassifieds.models.get_webp_upload_path),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to=farmclassifieds.models.get_image_upload_path),
        ),
    ]
