# Generated by Django 4.2.27 on 2025-12-11 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmclassifieds', '0002_adimage_webp_image_alter_adimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
