# Generated by Django 4.2.27 on 2025-12-11 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmclassifieds', '0003_alter_adpost_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
