# Generated by Django 4.2.27 on 2025-12-12 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmclassifieds', '0004_alter_adpost_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpost',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adpost',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adpost',
            name='renew_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='ad_post_limit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
