# Generated by Django 4.2.27 on 2025-12-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmclassifieds', '0005_adpost_expires_at_adpost_is_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price if fixed', max_digits=10, null=True),
        ),
    ]
