# Generated by Django 4.2.27 on 2025-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmclassifieds', '0006_adpost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price ', max_digits=10, null=True),
        ),
    ]
