# Generated by Django 4.2.27 on 2025-12-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmclassifieds', '0007_user_is_verified_seller_alter_adpost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='district',
            field=models.CharField(choices=[('alappuzha', 'Alappuzha'), ('ernakulam', 'Ernakulam'), ('idukki', 'Idukki'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod'), ('kollam', 'Kollam'), ('kottayam', 'Kottayam'), ('kozhikode', 'Kozhikode'), ('malappuram', 'Malappuram'), ('palakkad', 'Palakkad'), ('pathanamthitta', 'Pathanamthitta'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('thrissur', 'Thrissur'), ('wayanad', 'Wayanad')], max_length=30),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
