# Generated by Django 4.2.27 on 2025-12-29 05:16

from django.db import migrations, models
import farmclassifieds.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmclassifieds', '0008_alter_adpost_district_alter_adpost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=farmclassifieds.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='category',
            field=models.CharField(choices=[('fish', 'മത്സ്യം'), ('chicken', 'കോഴി'), ('duck', 'താറാവ്'), ('other_birds', 'മറ്റ് പക്ഷികൾ'), ('cow', 'പശു'), ('goat', 'ആട്'), ('buffalo', 'എരുമ'), ('agri_produce', 'കൃഷി ഉൽപ്പന്നങ്ങൾ'), ('seeds', 'വിത്തുകൾ'), ('dogs', 'നായ'), ('cats', 'പൂച്ച'), ('equipment', 'കൃഷി ഉപകരണങ്ങൾ'), ('other', 'മറ്റ്')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='district',
            field=models.CharField(choices=[('alappuzha', 'ആലപ്പുഴ'), ('ernakulam', 'എറണാകുളം'), ('idukki', 'ഇടുക്കി'), ('kannur', 'കണ്ണൂർ'), ('kasaragod', 'കാസർഗോഡ്'), ('kollam', 'കൊല്ലം'), ('kottayam', 'കോട്ടയം'), ('kozhikode', 'കോഴിക്കോട്'), ('malappuram', 'മലപ്പുറം'), ('palakkad', 'പാലക്കാട്'), ('pathanamthitta', 'പത്തനംതിട്ട'), ('thiruvananthapuram', 'തിരുവനന്തപുരം'), ('thrissur', 'തൃശൂർ'), ('wayanad', 'വയനാട്')], max_length=30),
        ),
    ]
